User.create(username: "Bobby")
User.create(username: "Billie")
User.create(username: "Marju")
User.create(username: "Nico")
Category.create(name: "US Politics")
Category.create(name: "Music")
Category.create(name: "Blockchain")
Category.create(name: "Art")
Category.create(name: "Theatre")
Category.create(name: "World")
Category.create(name: "Finance")
Category.create(name: "Education")
CategoryUser.create(category_id: 2, user_id: 1)
CategoryUser.create(category_id: 4, user_id: 1)
CategoryUser.create(category_id: 5, user_id: 1)
CategoryUser.create(category_id: 3, user_id: 2)
CategoryUser.create(category_id: 6, user_id: 2)
CategoryUser.create(category_id: 1, user_id: 2)
CategoryUser.create(category_id: 7, user_id: 2)
CategoryUser.create(category_id: 8, user_id: 2)
CategoryUser.create(category_id: 2, user_id: 3)
CategoryUser.create(category_id: 1, user_id: 3)
CategoryUser.create(category_id: 5, user_id: 3)
CategoryUser.create(category_id: 1, user_id: 4)
CategoryUser.create(category_id: 2, user_id: 4)
CategoryUser.create(category_id: 3, user_id: 4)
CategoryUser.create(category_id: 4, user_id: 4)
CategoryUser.create(category_id: 5, user_id: 4)
CategoryUser.create(category_id: 6, user_id: 4)
CategoryUser.create(category_id: 7, user_id: 4)
CategoryUser.create(category_id: 8, user_id: 4)